export const PORCELAIN = '#ECF0F1'; // LAUNCH BG
export const DODGER_BLUE = '#1A9AF0'; // BACK_TXT, TAB_BG. HEADER_TITLE_COLOR
export const WHITE = '#FFFFFF'; // TAB_BAR_ACTIVE, SETTING_TXT, LIST_HEADER_TXT
export const GEYSER = '#CED6E0'; //TAB_BAR_INACTIVE
// export const SETTING_BG = '#2f3542';
export const SHAMROCK = '#2ECC71';
export const DARK_GREY = '#121212';
export const WHISPER = '#F5F6FA';
export const CONCRETE = '#F2F2F2';
export const RED_PIGMENT = '#EA2027';
export const DRACULA_ORCHID = '#2d3436'
export const COPY_GREY = '#8C95A3'; // for copyright notice
